spring.application.name=healthcare-backend

# Render dynamic port
server.port=${PORT:8080}

# PostgreSQL (Render Internal DB)
spring.datasource.url=jdbc:postgresql://dpg-d7md7breo5us73eo9ni0-a:5432/healthcare_db_qkfw
spring.datasource.username=healthcare_user
spring.datasource.password=voUGwABc8u7IlTnIXBSRuTFv8fsvVVSL
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect